site_name: "metametameta"
site_url: "https://metametameta.readthedocs.io/"
site_author: "Matthew Dean Martin <matthewdeanmartin@gmail.com>"
site_description: "Documentation of metametameta, a tool for updating __about__.py from project files."

repo_url: "https://github.com/matthewdeanmartin/metametameta"

theme:
  name: readthedocs
  features:
    - navigation.footer

edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true


nav:
  - "Home": index.md
  - "Installation": installation.md
  - "Usage": usage.md
  - "Contributing": contributing.md
  - "Changelog": changelog.md

validation:
  nav:
    omitted_files: warn
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6

plugins:
  - search
  - mkdocstrings