name: Build and Test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.11'
          # cache: 'pipenv' # caching pipenv dependencies
      - name: Install poetry and pipx
        run: |
          pip install poetry && pip install pipx

      - name: Install global dependencies
        run: |
          pipx install isort && pipx install black && pipx install bandit && \
          pipx install pylint && pipx install pre-commit && pipx install poetry

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Makefile
        run: make check
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}