name: Docs

on:
  push:
    paths:
      - README.md
      - docs/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material mkdocstrings[python]
    - name: Deploy
      run: mkdocs gh-deploy --force
