name: Docs

on:
  push:
    paths:
      - README.md
      - docs/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material mkdocstrings[python]
    - name: Deploy
      run: mkdocs gh-deploy --force
