name: Publish

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/metametameta
    permissions:
      id-token: write
    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - name: Install poetry and pipx
      run: |
        pip install poetry && pip install pipx
    - name: Install global dependencies
      run: |
        pipx install isort && pipx install black && pipx install bandit && \
        pipx install pylint && pipx install pre-commit && pipx install poetry
    - name: Install Dependencies
      run: poetry install --with dev
    - name: Build package
      run: poetry run make publish
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
