# .github/workflows/publish-to-pypi.yml

name: Publish metametameta to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.14'

    - name: Install uv and pipx
      run: |
        pip install uv && pip install pipx

    - name: Install global dependencies
      run: |
        pipx install uv && pipx install "coderoller" && \
        pipx install isort && pipx install black && pipx install bandit && \
        pipx install pylint && pipx install pre-commit && pipx install uv && pipx install hatch && \
        pipx install cli_tool_audit

    - name: Install Dependencies
      run: uv sync

    - name: Run just check
      run: chmod +x scripts/*.sh && uv run just check

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Run just publish
      run: uv run just publish

    - name: Upload Package
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: packages
        path: dist/
        if-no-files-found: error
        retention-days: 1

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/metametameta
    permissions:
      id-token: write
    needs: build
    steps:
    - name: Fail if branch is not main
      if: github.event_name == 'workflow_dispatch' && github.ref != 
        'refs/heads/main'
      run: |
        echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
        exit 1
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Download artifact
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: packages
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
